/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoachesRouteImport } from './routes/coaches'
import { Route as EmpleadosRouteImport } from './routes/empleados'
import { Route as MiembrosRouteImport } from './routes/miembros'
import { Route as SuscripcionesRouteImport } from './routes/suscripciones'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesRoute = CoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpleadosRoute = EmpleadosRouteImport.update({
  id: '/empleados',
  path: '/empleados',
  getParentRoute: () => rootRouteImport,
} as any)
const MiembrosRoute = MiembrosRouteImport.update({
  id: '/miembros',
  path: '/miembros',
  getParentRoute: () => rootRouteImport,
} as any)
const SuscripcionesRoute = SuscripcionesRouteImport.update({
  id: '/suscripciones',
  path: '/suscripciones',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coaches': typeof CoachesRoute
  '/empleados': typeof EmpleadosRoute
  '/miembros': typeof MiembrosRoute
  '/suscripciones': typeof SuscripcionesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coaches': typeof CoachesRoute
  '/empleados': typeof EmpleadosRoute
  '/miembros': typeof MiembrosRoute
  '/suscripciones': typeof SuscripcionesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coaches': typeof CoachesRoute
  '/empleados': typeof EmpleadosRoute
  '/miembros': typeof MiembrosRoute
  '/suscripciones': typeof SuscripcionesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/coaches' | '/empleados' | '/miembros' | '/suscripciones'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/coaches' | '/empleados' | '/miembros' | '/suscripciones'
  id:
    | '__root__'
    | '/'
    | '/coaches'
    | '/empleados'
    | '/miembros'
    | '/suscripciones'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoachesRoute: typeof CoachesRoute
  EmpleadosRoute: typeof EmpleadosRoute
  MiembrosRoute: typeof MiembrosRoute
  SuscripcionesRoute: typeof SuscripcionesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches': {
      id: '/coaches'
      path: '/coaches'
      fullPath: '/coaches'
      preLoaderRoute: typeof CoachesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empleados': {
      id: '/empleados'
      path: '/empleados'
      fullPath: '/empleados'
      preLoaderRoute: typeof EmpleadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/miembros': {
      id: '/miembros'
      path: '/miembros'
      fullPath: '/miembros'
      preLoaderRoute: typeof MiembrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suscripciones': {
      id: '/suscripciones'
      path: '/suscripciones'
      fullPath: '/suscripciones'
      preLoaderRoute: typeof SuscripcionesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoachesRoute: CoachesRoute,
  EmpleadosRoute: EmpleadosRoute,
  MiembrosRoute: MiembrosRoute,
  SuscripcionesRoute: SuscripcionesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
